### ISSUE TITLE
LinkPreview: Add argument "includeDescription" 

### ISSUE THREAD

**Issue by rbrands** [MSiccDev/LinkTools#1]
I like your LinkPreview and have forked it. One suggestion: Add argument includeDescription to GetLinkDataAsync as in [my implementation](https://github.com/rbrands/LinkTools/blob/e0604875682b6a26f56d61f92c752b34598cafbc/src/LinkPreview/Service/ILinkPreviewService.cs#L11) and implement it in GetLinkDataAsync as in [my code](https://github.com/rbrands/LinkTools/blob/e0604875682b6a26f56d61f92c752b34598cafbc/src/LinkPreview/Service/LinkPreviewService.cs#L58)

**Comment by MSicc** [comment]
Hi, sorry for the late reply. You're right, this is basically a no brainer. Would you mind to submit a pull request?

**Comment by MSicc** [comment]
implemented as of today by myself.
